/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAdjustIndexRouteImport } from './routes/_authenticated/adjust/index'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history/index'
import { Route as AuthenticatedICodeRouteImport } from './routes/_authenticated/i/$code'
import { Route as AuthenticatedItemIdRouteImport } from './routes/_authenticated/item/$id'
import { Route as AuthenticatedQrIndexRouteImport } from './routes/_authenticated/qr/index'
import { Route as AuthenticatedReceiveIndexRouteImport } from './routes/_authenticated/receive/index'
import { Route as AuthenticatedSaleIndexRouteImport } from './routes/_authenticated/sale/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsLookupsRouteImport } from './routes/_authenticated/settings/lookups'
import { Route as AuthenticatedSettingsStoresRouteImport } from './routes/_authenticated/settings/stores'
import { Route as AuthenticatedStockIndexRouteImport } from './routes/_authenticated/stock/index'
import { Route as AuthenticatedTransferIndexRouteImport } from './routes/_authenticated/transfer/index'
import { Route as AuthenticatedWithdrawIndexRouteImport } from './routes/_authenticated/withdraw/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdjustIndexRoute =
  AuthenticatedAdjustIndexRouteImport.update({
    id: '/adjust/',
    path: '/adjust/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedICodeRoute = AuthenticatedICodeRouteImport.update({
  id: '/i/$code',
  path: '/i/$code',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemIdRoute = AuthenticatedItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQrIndexRoute = AuthenticatedQrIndexRouteImport.update({
  id: '/qr/',
  path: '/qr/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReceiveIndexRoute =
  AuthenticatedReceiveIndexRouteImport.update({
    id: '/receive/',
    path: '/receive/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSaleIndexRoute = AuthenticatedSaleIndexRouteImport.update({
  id: '/sale/',
  path: '/sale/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLookupsRoute =
  AuthenticatedSettingsLookupsRouteImport.update({
    id: '/lookups',
    path: '/lookups',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsStoresRoute =
  AuthenticatedSettingsStoresRouteImport.update({
    id: '/stores',
    path: '/stores',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedStockIndexRoute = AuthenticatedStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransferIndexRoute =
  AuthenticatedTransferIndexRouteImport.update({
    id: '/transfer/',
    path: '/transfer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWithdrawIndexRoute =
  AuthenticatedWithdrawIndexRouteImport.update({
    id: '/withdraw/',
    path: '/withdraw/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/i/$code': typeof AuthenticatedICodeRoute
  '/item/$id': typeof AuthenticatedItemIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/lookups': typeof AuthenticatedSettingsLookupsRoute
  '/settings/stores': typeof AuthenticatedSettingsStoresRoute
  '/adjust/': typeof AuthenticatedAdjustIndexRoute
  '/history/': typeof AuthenticatedHistoryIndexRoute
  '/qr/': typeof AuthenticatedQrIndexRoute
  '/receive/': typeof AuthenticatedReceiveIndexRoute
  '/sale/': typeof AuthenticatedSaleIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/stock/': typeof AuthenticatedStockIndexRoute
  '/transfer/': typeof AuthenticatedTransferIndexRoute
  '/withdraw/': typeof AuthenticatedWithdrawIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/i/$code': typeof AuthenticatedICodeRoute
  '/item/$id': typeof AuthenticatedItemIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/lookups': typeof AuthenticatedSettingsLookupsRoute
  '/settings/stores': typeof AuthenticatedSettingsStoresRoute
  '/adjust': typeof AuthenticatedAdjustIndexRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
  '/qr': typeof AuthenticatedQrIndexRoute
  '/receive': typeof AuthenticatedReceiveIndexRoute
  '/sale': typeof AuthenticatedSaleIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/stock': typeof AuthenticatedStockIndexRoute
  '/transfer': typeof AuthenticatedTransferIndexRoute
  '/withdraw': typeof AuthenticatedWithdrawIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/i/$code': typeof AuthenticatedICodeRoute
  '/_authenticated/item/$id': typeof AuthenticatedItemIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/lookups': typeof AuthenticatedSettingsLookupsRoute
  '/_authenticated/settings/stores': typeof AuthenticatedSettingsStoresRoute
  '/_authenticated/adjust/': typeof AuthenticatedAdjustIndexRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
  '/_authenticated/qr/': typeof AuthenticatedQrIndexRoute
  '/_authenticated/receive/': typeof AuthenticatedReceiveIndexRoute
  '/_authenticated/sale/': typeof AuthenticatedSaleIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/stock/': typeof AuthenticatedStockIndexRoute
  '/_authenticated/transfer/': typeof AuthenticatedTransferIndexRoute
  '/_authenticated/withdraw/': typeof AuthenticatedWithdrawIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/i/$code'
    | '/item/$id'
    | '/settings/account'
    | '/settings/general'
    | '/settings/lookups'
    | '/settings/stores'
    | '/adjust/'
    | '/history/'
    | '/qr/'
    | '/receive/'
    | '/sale/'
    | '/settings/'
    | '/stock/'
    | '/transfer/'
    | '/withdraw/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/i/$code'
    | '/item/$id'
    | '/settings/account'
    | '/settings/general'
    | '/settings/lookups'
    | '/settings/stores'
    | '/adjust'
    | '/history'
    | '/qr'
    | '/receive'
    | '/sale'
    | '/settings'
    | '/stock'
    | '/transfer'
    | '/withdraw'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/i/$code'
    | '/_authenticated/item/$id'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/lookups'
    | '/_authenticated/settings/stores'
    | '/_authenticated/adjust/'
    | '/_authenticated/history/'
    | '/_authenticated/qr/'
    | '/_authenticated/receive/'
    | '/_authenticated/sale/'
    | '/_authenticated/settings/'
    | '/_authenticated/stock/'
    | '/_authenticated/transfer/'
    | '/_authenticated/withdraw/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adjust/': {
      id: '/_authenticated/adjust/'
      path: '/adjust'
      fullPath: '/adjust/'
      preLoaderRoute: typeof AuthenticatedAdjustIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/i/$code': {
      id: '/_authenticated/i/$code'
      path: '/i/$code'
      fullPath: '/i/$code'
      preLoaderRoute: typeof AuthenticatedICodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/item/$id': {
      id: '/_authenticated/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof AuthenticatedItemIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qr/': {
      id: '/_authenticated/qr/'
      path: '/qr'
      fullPath: '/qr/'
      preLoaderRoute: typeof AuthenticatedQrIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receive/': {
      id: '/_authenticated/receive/'
      path: '/receive'
      fullPath: '/receive/'
      preLoaderRoute: typeof AuthenticatedReceiveIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sale/': {
      id: '/_authenticated/sale/'
      path: '/sale'
      fullPath: '/sale/'
      preLoaderRoute: typeof AuthenticatedSaleIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/lookups': {
      id: '/_authenticated/settings/lookups'
      path: '/lookups'
      fullPath: '/settings/lookups'
      preLoaderRoute: typeof AuthenticatedSettingsLookupsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/stores': {
      id: '/_authenticated/settings/stores'
      path: '/stores'
      fullPath: '/settings/stores'
      preLoaderRoute: typeof AuthenticatedSettingsStoresRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/stock/': {
      id: '/_authenticated/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof AuthenticatedStockIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfer/': {
      id: '/_authenticated/transfer/'
      path: '/transfer'
      fullPath: '/transfer/'
      preLoaderRoute: typeof AuthenticatedTransferIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/withdraw/': {
      id: '/_authenticated/withdraw/'
      path: '/withdraw'
      fullPath: '/withdraw/'
      preLoaderRoute: typeof AuthenticatedWithdrawIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsLookupsRoute: typeof AuthenticatedSettingsLookupsRoute
  AuthenticatedSettingsStoresRoute: typeof AuthenticatedSettingsStoresRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsLookupsRoute: AuthenticatedSettingsLookupsRoute,
  AuthenticatedSettingsStoresRoute: AuthenticatedSettingsStoresRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedICodeRoute: typeof AuthenticatedICodeRoute
  AuthenticatedItemIdRoute: typeof AuthenticatedItemIdRoute
  AuthenticatedAdjustIndexRoute: typeof AuthenticatedAdjustIndexRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
  AuthenticatedQrIndexRoute: typeof AuthenticatedQrIndexRoute
  AuthenticatedReceiveIndexRoute: typeof AuthenticatedReceiveIndexRoute
  AuthenticatedSaleIndexRoute: typeof AuthenticatedSaleIndexRoute
  AuthenticatedStockIndexRoute: typeof AuthenticatedStockIndexRoute
  AuthenticatedTransferIndexRoute: typeof AuthenticatedTransferIndexRoute
  AuthenticatedWithdrawIndexRoute: typeof AuthenticatedWithdrawIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedICodeRoute: AuthenticatedICodeRoute,
  AuthenticatedItemIdRoute: AuthenticatedItemIdRoute,
  AuthenticatedAdjustIndexRoute: AuthenticatedAdjustIndexRoute,
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
  AuthenticatedQrIndexRoute: AuthenticatedQrIndexRoute,
  AuthenticatedReceiveIndexRoute: AuthenticatedReceiveIndexRoute,
  AuthenticatedSaleIndexRoute: AuthenticatedSaleIndexRoute,
  AuthenticatedStockIndexRoute: AuthenticatedStockIndexRoute,
  AuthenticatedTransferIndexRoute: AuthenticatedTransferIndexRoute,
  AuthenticatedWithdrawIndexRoute: AuthenticatedWithdrawIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
