/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history/index'
import { Route as AuthenticatedReceiveIndexRouteImport } from './routes/_authenticated/receive/index'
import { Route as AuthenticatedStockIndexRouteImport } from './routes/_authenticated/stock/index'
import { Route as AuthenticatedWithdrawIndexRouteImport } from './routes/_authenticated/withdraw/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReceiveIndexRoute =
  AuthenticatedReceiveIndexRouteImport.update({
    id: '/receive/',
    path: '/receive/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStockIndexRoute = AuthenticatedStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWithdrawIndexRoute =
  AuthenticatedWithdrawIndexRouteImport.update({
    id: '/withdraw/',
    path: '/withdraw/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/history/': typeof AuthenticatedHistoryIndexRoute
  '/receive/': typeof AuthenticatedReceiveIndexRoute
  '/stock/': typeof AuthenticatedStockIndexRoute
  '/withdraw/': typeof AuthenticatedWithdrawIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
  '/receive': typeof AuthenticatedReceiveIndexRoute
  '/stock': typeof AuthenticatedStockIndexRoute
  '/withdraw': typeof AuthenticatedWithdrawIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
  '/_authenticated/receive/': typeof AuthenticatedReceiveIndexRoute
  '/_authenticated/stock/': typeof AuthenticatedStockIndexRoute
  '/_authenticated/withdraw/': typeof AuthenticatedWithdrawIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/history/' | '/receive/' | '/stock/' | '/withdraw/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/history' | '/receive' | '/stock' | '/withdraw'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/history/'
    | '/_authenticated/receive/'
    | '/_authenticated/stock/'
    | '/_authenticated/withdraw/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receive/': {
      id: '/_authenticated/receive/'
      path: '/receive'
      fullPath: '/receive/'
      preLoaderRoute: typeof AuthenticatedReceiveIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock/': {
      id: '/_authenticated/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof AuthenticatedStockIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/withdraw/': {
      id: '/_authenticated/withdraw/'
      path: '/withdraw'
      fullPath: '/withdraw/'
      preLoaderRoute: typeof AuthenticatedWithdrawIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
  AuthenticatedReceiveIndexRoute: typeof AuthenticatedReceiveIndexRoute
  AuthenticatedStockIndexRoute: typeof AuthenticatedStockIndexRoute
  AuthenticatedWithdrawIndexRoute: typeof AuthenticatedWithdrawIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
  AuthenticatedReceiveIndexRoute: AuthenticatedReceiveIndexRoute,
  AuthenticatedStockIndexRoute: AuthenticatedStockIndexRoute,
  AuthenticatedWithdrawIndexRoute: AuthenticatedWithdrawIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
