-- การตั้งค่า: คลัง (แก้/เพิ่ม/ปิด) · ตัวเลือกที่ใช้บ่อย (lookup_values) · ค่าระบบ (app_settings)
--
-- ออกแบบเผื่ออนาคต
-- * lookup_values ใช้ category แยกประเภท — เพิ่มประเภทใหม่ (เช่น grape, region) ได้โดยแก้ check constraint
-- * app_settings เป็น key/value (jsonb) — เพิ่มค่าตั้งค่าใหม่ได้โดยไม่ต้องเพิ่มคอลัมน์
-- * ไม่มีการลบ ใช้ is_active = false แทน (ข้อมูลเดิมที่อ้างถึงยังอยู่)
-- * ตอนนี้ทุกคนที่ login แก้ได้ เมื่อมีระบบสิทธิ์ให้เปลี่ยน policy insert/update เป็นเฉพาะ admin

-- ─── stores: เพิ่ม/แก้/ปิดได้ ──────────────────────────────────────────────────
alter table public.stores add column is_active boolean not null default true;
alter table public.stores alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('public.stores', 'id'), (select max(id) from public.stores));
alter table public.stores add constraint stores_code_chk check (code ~ '^[A-Z0-9_-]{1,12}$');
alter table public.stores add constraint stores_name_chk check (btrim(name) <> '');

create trigger stores_audit before update on public.stores
  for each row execute function public.set_updated_audit();

-- ปิดคลังที่ยังมีไวน์คงเหลือไม่ได้
create or replace function public.stores_guard_deactivate()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.is_active and not new.is_active and exists (
    select 1 from public.stock_items where store_id = new.id and deleted_at is null and balance > 0
  ) then
    raise exception 'ปิดคลัง % ไม่ได้ เพราะยังมีไวน์คงเหลือ', new.name;
  end if;
  return new;
end;
$$;
create trigger stores_guard before update on public.stores
  for each row execute function public.stores_guard_deactivate();

grant insert (code, name, sort_order, is_active) on public.stores to authenticated;
grant update (code, name, sort_order, is_active) on public.stores to authenticated;
create policy "เพิ่มคลังได้เมื่อ login" on public.stores for insert to authenticated with check (true);
create policy "แก้คลังได้เมื่อ login" on public.stores for update to authenticated using (true) with check (true);

-- ─── lookup_values: ตัวเลือกที่ใช้บ่อย ──────────────────────────────────────────
create table public.lookup_values (
  id          uuid primary key default gen_random_uuid(),
  category    text not null check (category in ('country', 'supplier', 'rack')),
  -- ใช้กับ rack (ชั้นวางของคลังไหน) ประเภทอื่นเป็น null
  store_id    smallint references public.stores (id),
  value       text not null check (btrim(value) <> ''),
  sort_order  integer not null default 0,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  created_by  uuid default auth.uid(),
  updated_at  timestamptz not null default now(),
  updated_by  uuid default auth.uid(),
  constraint lookup_values_rack_store_chk check ((category = 'rack') = (store_id is not null))
);
create unique index lookup_values_uq
  on public.lookup_values (category, coalesce(store_id, 0), lower(btrim(value)));

create trigger lookup_values_audit before update on public.lookup_values
  for each row execute function public.set_updated_audit();

alter table public.lookup_values enable row level security;
create policy "อ่านได้เมื่อ login" on public.lookup_values for select to authenticated using (true);
create policy "เพิ่มได้เมื่อ login" on public.lookup_values for insert to authenticated with check (true);
create policy "แก้ได้เมื่อ login" on public.lookup_values for update to authenticated using (true) with check (true);
revoke delete on public.lookup_values from anon, authenticated;

insert into public.lookup_values (category, value, sort_order)
select 'country', v, row_number() over ()
from unnest(array['France', 'Italy', 'Spain', 'Portugal', 'Germany', 'Austria', 'USA', 'Australia',
                  'New Zealand', 'Chile', 'Argentina', 'South Africa', 'Japan', 'Thailand']) as v;

-- ─── app_settings: ค่าระบบแบบ key/value ───────────────────────────────────────
create table public.app_settings (
  key         text primary key check (key ~ '^[a-z][a-z0-9_]*$'),
  value       jsonb not null,
  created_at  timestamptz not null default now(),
  created_by  uuid default auth.uid(),
  updated_at  timestamptz not null default now(),
  updated_by  uuid default auth.uid()
);

create trigger app_settings_audit before update on public.app_settings
  for each row execute function public.set_updated_audit();

alter table public.app_settings enable row level security;
create policy "อ่านได้เมื่อ login" on public.app_settings for select to authenticated using (true);
create policy "เพิ่มได้เมื่อ login" on public.app_settings for insert to authenticated with check (true);
create policy "แก้ได้เมื่อ login" on public.app_settings for update to authenticated using (true) with check (true);
revoke delete on public.app_settings from anon, authenticated;

-- ค่าเริ่มต้น (หน้าเว็บมีค่า default ของตัวเองด้วย ถ้า key ไม่มีในตาราง)
insert into public.app_settings (key, value) values
  ('default_receive_store_id', 'null'),
  ('low_stock_threshold', '2'),
  ('require_withdraw_note', 'false');
